# Generated by Django 3.0.5 on 2020-04-05 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModulesPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=200)),
                ('typeOf', models.IntegerField(default=0)),
                ('size', models.FloatField(default=0)),
                ('door', models.BooleanField(default=False)),
            ],
        ),
    ]
