# Generated by Django 3.0.5 on 2020-04-07 16:35

from django.db import migrations, models
import precios.models


class Migration(migrations.Migration):

    dependencies = [
        ('precios', '0004_modulesprice_interiorblanco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulesprice',
            name='typeOf',
            field=models.CharField(choices=[(precios.models.Modules['CAJONERA'], 'CAJONERA'), (precios.models.Modules['COLGADOR'], 'COLGADOR'), (precios.models.Modules['REPISERO'], 'REPISERO')], max_length=20),
        ),
    ]
