# Generated by Django 3.0.5 on 2020-04-07 16:40

from django.db import migrations, models
import precios.models


class Migration(migrations.Migration):

    dependencies = [
        ('precios', '0005_auto_20200407_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulesprice',
            name='typeOf',
            field=models.CharField(choices=[(precios.models.Modules['CAJONERA'], 'CAJONERAS'), (precios.models.Modules['COLGADOR'], 'COLGADORES'), (precios.models.Modules['REPISERO'], 'REPISEROS')], max_length=20),
        ),
    ]
