# Generated by Django 3.0.5 on 2020-04-07 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precios', '0006_auto_20200407_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulesprice',
            name='typeOf',
            field=models.CharField(choices=[('CAJONERA', 'Cajonera'), ('COLGADOR', 'Colgador'), ('REPISERO', 'Repisero')], max_length=20),
        ),
    ]
