# Generated by Django 3.0.5 on 2020-04-08 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precios', '0007_auto_20200407_1145'),
    ]

    operations = [
        migrations.CreateModel(
            name='Textures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='NONE', max_length=100)),
                ('img', models.ImageField(upload_to='')),
            ],
        ),
    ]
