# Generated by Django 3.0.5 on 2020-04-08 09:18

from django.db import migrations, models
import precios.storage


class Migration(migrations.Migration):

    dependencies = [
        ('precios', '0010_auto_20200408_0417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textures',
            name='img',
            field=models.ImageField(max_length=9999, storage=precios.storage.OverwriteStorage(), upload_to='Textures'),
        ),
    ]
