# Generated by Django 3.0.5 on 2020-05-13 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precios', '0011_auto_20200408_0418'),
    ]

    operations = [
        migrations.AddField(
            model_name='textures',
            name='space',
            field=models.FloatField(default=0),
        ),
    ]
